version: '3.2'

services:
  registry:
    restart: always
    image: registry:2
    ports:
      - "5000:5000"  
    volumes:
      - /opt/registry_data/:/var/lib/registry
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]




