version: "3.2"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 3000:80/tcp
    volumes:
      - /opt/adguard/conf/:/opt/adguardhome/conf
      - /opt/adguard/work/:/opt/adguardhome/work
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

