version: '3.4'

services:
  samba:
    image: dperson/samba
    environment:
      TZ: 'Europe/Moscow'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    restart: unless-stopped
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    volumes:
      - /opt/backup_volume:/mnt:z
    command: '-s "public;/mnt;yes;no;no;andrei" -u "andrei;{{ PASSWORD }}" -p'

networks:
  default: